config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :tweets do
    post 'likes', to: 'tweets#likes'
    post 'retweet', to: 'tweets#retweet'
    get 'detail', to: 'tweets#detail'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  post 'follow/:user_id', to: 'users#follow', as: 'users_follow'
  get 'home/index'
  get 'all_tweets', to: 'home#all_tweets', as: 'all_tweets'
  get 'home/profile'

  root 'home#index'

  #rutas api
  resources :api, path: '/api/news'
  get '/api/:date1/:date2' => 'dates#show'
  get '/api/create' => 'api#create'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        if signed_in?
          if( params[:search] && !params[:search].empty? )
            @tweets = Tweet.tweets_for_me(current_user).where("content LIKE ?", "%#{params[:search]}%").order(created_at: :desc).page params[:page]
          else
            @tweets = Tweet.tweets_for_me(current_user).order(created_at: :desc).page params[:page]
          end
          @tweet = Tweet.new
        else
          @tweets = Tweet.order(created_at: 'desc').page params[:page]
          redirect_to all_tweets_path
        end
      end
    
      def all_tweets
        if( params[:search] && !params[:search].empty? )
          @tweets = Tweet.where("content LIKE ?", "%#{params[:search]}%").order(created_at: :desc).page params[:page]
        else
          @tweets = Tweet.order(created_at: 'desc').page params[:page]
        end
    
      end
    
      def profile
        if current_user.present?
          @following = current_user.users_followed
          @follower = current_user.my_follower
          @likes = current_user.my_likes.order(created_at: :desc).page params[:page]
          @retweets = current_user.retweets_give_it_now.order(created_at: :desc).page params[:page]
          @tweets = current_user.my_tweets.order(created_at: :desc).page params[:page]
          @followed = current_user.users_followed.count
          @follow = Friend.where(friend_id: current_user).count
        else
          redirect_to new_user_session_path
        end
      end
    
    
    
    end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/all_tweets.html.erb
<div class="color-black">
    <div class="border-down pt-1 pl-4">
        <h5 class=""><%= link_to '<i class="fas fa-long-arrow-alt-left fa-lg color-blue"></i>'.html_safe, root_path %>&nbsp;&nbsp;Explorar</h5>
    </div>
    
    <% @tweets.each do |tweet| %>
        <%= render "shared/card_tweet", tweet: tweet %>
    <% end %>
    
    <div class="p-4">
        <div class="text-center">
            <%= link_to_prev_page @tweets, "Show less Tweets", class: "btn btn-primary btn-sm text-11" %>
            <i class="btn btn-light btn-sm text-13 "><%= @tweets.current_page %></i>
            <%= link_to_next_page @tweets, "Show more Tweets", class:"btn btn-primary btn-sm text-11"%>
        </div>
    </div>
    <%#= paginate @tweets %>
</div>

app/views/home/index.html.erb
<div class="container content-sec color-black">
    <%= render "shared/messages"%>

    <% if user_signed_in? %>
        <div class="border-down">
            <div class="row justify-content-md-center">
                <div class="col-1 mr-3">
                    <%= image_tag(current_user.photo_url, class: "photo-avatar rounded-circle", alt: "Avatar Session")%>
                </div>
                <div class="col-9">
                <%= render 'tweets/form', tweet: @tweet %>
                </div>
            </div>
        </div>
    <% end %>

    <% @tweets.each do |tweet| %>
        <span></span>
        
        <article class="mytwitter-post py-3"> 
            <div class="row justify-content-md-center">
                <div class="col-1">
                    <%= image_tag(tweet.user.photo_url, class: "photo-avatar-post rounded-circle ", alt: "Avatar Post")%>
                </div>
                <div class="col-9">
                    <span class="text-11 color-time"><%= link_to '<i class=" fas fa-history" aria-hidden="true"></i> '.html_safe+distance_of_time_in_words(Time.now, tweet.created_at), tweet, class: "color-time text-decoration-none" %></span>
                    <div>
                        <i class="text-13 color-blue-deep"><strong>@<%= tweet.user.username.capitalize %></strong></i>
                    </div>
                    <div class="text-11 border-down-white pb-2">
                            <% if tweet.is_retweet?%>
                                <%=  link_to "", tweet.tweet_ref, class:"fas fa-retweet fa-lg text-success text-decoration-none" %>
                                <div class="row justify-content-md-center retweet-marco py-2 px-2">
                                    <div class="col-2">
                                        <%= image_tag(tweet.tweet_ref.user.photo_url, class: "photo-avatar-post-re rounded-circle ", style: "float:left;" ,alt: "Avatar Post")%>
                                    </div>
                                    <div class="col-10 " style="padding-left:0%; padding-right:10%;">
                                        <span class="text-11 color-time"><%= link_to '<i class=" fas fa-history" aria-hidden="true"></i> '.html_safe+distance_of_time_in_words(Time.now, tweet.tweet_ref.created_at), tweet, class: "color-time text-decoration-none" %></span>
                                        <br>
                                        <strong class="color-blue ">@<%= tweet.tweet_ref.user.username.capitalize %></strong>
                                        <br>
                                        <span><%= tweet.tweet_ref.content %></span>
                                    </div>
                                </div>
                            <% else %>
                                &nbsp;&nbsp;&nbsp;<%= tweet.content.html_safe %>
                            <% end %>
                    </div>

                    <div class="text-11 div-like-retweet pt-1">
                        <div class="row">
                            <div class="col-6">
                                <span>
                                    <% if tweet.is_liked?(current_user) %>
                                        <%= link_to '<i class="fas fa-heart"></i>'.html_safe, tweet_likes_path(tweet), method: :post, class: "text-danger" %>
                                    <% else %>
                                        <%= link_to '<i class="far fa-heart"></i>'.html_safe, tweet_likes_path(tweet),method: :post, class: "text-black" %>
                                    <% end %>
                                    &nbsp;&nbsp;<%= tweet.likes.count %>
                                </span>
                            </div>
                            <div class="col-6">
                                <span>
                                    <% if tweet.is_rt?(current_user, tweet) %>
                                        <%= link_to '', tweet_retweet_path(tweet), method: :post, class: "fas fa-retweet text-black text-decoration-none" %>
                                    <% else %>
                                        <%= link_to '', tweet_retweet_path(tweet), method: :post, class: "fas fa-retweet text-warning text-decoration-none" %>
                                    <% end %>
                                    &nbsp;&nbsp;<%= tweet.count_rt %>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </article>
    <% end %>

    <div class="p-4">
        <div class="text-center">
            <%= link_to_prev_page @tweets, "Show less Tweets", class: "btn btn-primary btn-sm text-11" %>
            <i class="btn btn-light btn-sm text-13 "><%= @tweets.current_page %></i>
            <%= link_to_next_page @tweets, "Shore more Tweets", class:"btn btn-primary btn-sm text-11"%>
        </div>
    </div>
    <%#= paginate @tweets %>
</div>